### ISSUE TITLE
Compile not working because pubxml in gitignore

### ISSUE THREAD

**Issue by anlx-sw** [Sleepw4lker/AdcsToRest#1]
Hi,
I just tried to compile the sln to play arround with it. unfortunatley on compile visual studio complains that the file 
`....\AdcsToRest\Properties\PublishProfiles\FolderProfile.pubxml` is missing.

I noticed in the gitignore that this filetype is removed.
 https://github.com/Sleepw4lker/AdcsToRest/blob/c53b930ec52963746db3040b1485103a3823e876/.gitignore#L187

Can you remove this line from the gitignore?

**Comment by anlx-sw** [comment]
this line might also be an issue:
https://github.com/Sleepw4lker/AdcsToRest/blob/c53b930ec52963746db3040b1485103a3823e876/.gitignore#L193

**Comment by Sleepw4lker** [comment]
Thanks for your feedback, I've just committed the change to .gitignore and the missing file. I'm eager for your feedback on the project. Reach out to me if you need assistance compiling or setting it up.
